name: Free Ubuntu RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 6 hours

    steps:
      - name: Install XFCE Desktop + RDP
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y \
            xrdp xfce4 xfce4-goodies dbus-x11 policykit-1 \
            firefox xterm
          
          # Configure XFCE as default session
          echo "startxfce4" > ~/.xsession
          echo "xfce4-session" | sudo tee /etc/skel/.xsession

          # Enable XRDP service
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

          # Allow RDP firewall port over Tailscale
          sudo ufw allow 3389 || true

      - name: Create RDP User with Secure Password
        run: |
          username="rdpuser"
          password=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)
          sudo useradd -m -s /bin/bash $username
          echo "$username:$password" | sudo chpasswd
          sudo usermod -aG sudo,video,audio $username
          echo "RDP_PASSWORD=$password" >> $GITHUB_ENV
          echo "RDP_USERNAME=$username" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-$GITHUB_RUN_ID
          tsIP=$(tailscale ip -4 | head -n1)
          if [ -z "$tsIP" ]; then
            echo "Tailscale IP not assigned. Exiting."
            exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV

      - name: Show Connection Info
        run: |
          echo ""
          echo "=== UBUNTU RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: $RDP_USERNAME"
          echo "Password: $RDP_PASSWORD"
          echo "========================="
          echo ""

      - name: Keep Alive
        run: |
          end=$((SECONDS+21600))  # 6 hours
          while [ $SECONDS -lt $end ]; do
            echo "[$(date)] RDP Active - still running..."
            sleep 300
          done
